# Generated by Django 5.2.4 on 2025-08-03 20:50

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_creator_alter_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(default=events.models.generate_event_code, max_length=10, unique=True),
        ),
    ]
