# Generated by Django 5.2.4 on 2025-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
