# Generated by Django 5.2.5 on 2025-09-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_profile_email'),
        ('events', '0010_question_author_name_alter_question_author_and_more'),
    ]

    operations = [
    ]
