# Generated by Django 5.2.5 on 2025-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_merge_20250905_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
